// Comprehensive mechanical keyboard switch database.
// Organized by manufacturer — full Gateron and Kailh lineups included
// alongside every other major brand. Used as the seed source for the
// SwitchEntry entity and as a client-side reference.

export const SWITCH_DATABASE = [
  // ── CHERRY MX ──────────────────────────────────────────────
  { name: "Cherry MX Red", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 45, description: "The classic light linear. Cherry's flagship switch — smooth, fast, and ubiquitous." },
  { name: "Cherry MX Red Silent", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 40, peak_decibels: 46, responsiveness_rating: 3, actuation_force: 45, description: "Silenced MX Red with internal damping bumpers for office-friendly quiet." },
  { name: "Cherry MX Black", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 3, actuation_force: 60, description: "Heavy linear switch favored by typists who want a firm bottom-out." },
  { name: "Cherry MX Brown", manufacturer: "Cherry", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 3, actuation_force: 45, description: "The gateway tactile. Subtle bump that introduced millions to non-clicky feel." },
  { name: "Cherry MX Blue", manufacturer: "Cherry", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 58, peak_decibels: 65, responsiveness_rating: 3, actuation_force: 50, description: "Iconic click-jacket switch. Loud, crisp, and divisive in shared spaces." },
  { name: "Cherry MX Clear", manufacturer: "Cherry", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 3, actuation_force: 55, description: "The enthusiast tactile. Stronger bump than Brown with a heavier spring." },
  { name: "Cherry MX Silver (Speed)", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 45, description: "Low-profile speed linear with a shortened actuation point for gaming." },
  { name: "Cherry MX Nature White", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 55, description: "Unlubed white-housing linear with a slightly heavier spring than Red." },
  { name: "Cherry MX Green", manufacturer: "Cherry", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 59, peak_decibels: 66, responsiveness_rating: 2, actuation_force: 80, description: "Heavy clicky switch — essentially a stiffer MX Blue." },
  { name: "Cherry MX Pale Blue", manufacturer: "Cherry", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 56, peak_decibels: 62, responsiveness_rating: 3, actuation_force: 50, description: "Click bar switch with a slightly softer click than MX Blue." },
  { name: "Cherry MX Tactile Grey", manufacturer: "Cherry", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 2, actuation_force: 80, description: "Heavy tactile for space bars and stiff-feeling builds." },
  { name: "Cherry MX Linear Grey", manufacturer: "Cherry", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 54, peak_decibels: 60, responsiveness_rating: 2, actuation_force: 80, description: "Heavy linear counterpart to the Tactile Grey — stiff and deliberate." },
  { name: "Cherry MX White", manufacturer: "Cherry", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 57, peak_decibels: 63, responsiveness_rating: 3, actuation_force: 50, description: "Click-bar switch with a cleaner click than the jacket-style MX Blue." },

  // ── GATERON ────────────────────────────────────────────────
  { name: "Gateron Red", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 46, peak_decibels: 52, responsiveness_rating: 4, actuation_force: 45, description: "Gateron's flagship linear — smoother and cheaper than MX Red." },
  { name: "Gateron Yellow (KS-3)", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 50, description: "Budget thocky linear. Heavier spring, famously smooth unlubed." },
  { name: "Gateron Black", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 3, actuation_force: 50, description: "Heavier linear for typists who want resistance without a bump." },
  { name: "Gateron Milky Red", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 45, peak_decibels: 51, responsiveness_rating: 4, actuation_force: 45, description: "Milky-housing Red with a deeper, creamier sound than standard." },
  { name: "Gateron Milky Yellow", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 50, description: "Milky-housing Yellow — deeper and more muted than the KS-3." },
  { name: "Gateron Oil King", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 55, description: "Factory-lubed linear with PA66 housing — buttery smooth and deep." },
  { name: "Gateron CJ", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 4, actuation_force: 50, description: "Collab linear with a unique POM stem — smooth with a clean bottom-out." },
  { name: "Gateron CAP Yellow", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 50, description: "CAP-series Yellow with redesigned stem for reduced wobble." },
  { name: "Gateron CAP Milky Yellow", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 50, description: "Milky CAP housing version — deeper and creamier than standard CAP." },
  { name: "Gateron Smoothie", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 46, peak_decibels: 52, responsiveness_rating: 5, actuation_force: 45, description: "UHMWPE stem linear — extremely smooth with a glassy, marbly sound." },
  { name: "Gateron Smoothie Silent", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 40, peak_decibels: 46, responsiveness_rating: 3, actuation_force: 45, description: "Silenced version of the Smoothie with factory damping bumpers." },
  { name: "Gateron Brown", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 3, actuation_force: 45, description: "Gateron's tactile — slightly more pronounced bump than Cherry Brown." },
  { name: "Gateron Clear", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 35, description: "Light-spring tactile — gentle bump for fast, low-effort typing." },
  { name: "Gateron Baby Kangaroo", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 50, description: "Medium-bump tactile with a snappy, clacky bottom-out." },
  { name: "Gateron Quark", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 45, description: "Top-housing tactile with a rounded, smooth bump." },
  { name: "Gateron Holy Panda", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Gateron's official Holy Panda — strong tactile bump with a deep thock." },
  { name: "Gateron Blue", manufacturer: "Gateron", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 58, peak_decibels: 64, responsiveness_rating: 3, actuation_force: 55, description: "Gateron's click-jacket switch — louder and snappier than Cherry Blue." },
  { name: "Gateron Green", manufacturer: "Gateron", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 59, peak_decibels: 65, responsiveness_rating: 2, actuation_force: 80, description: "Heavy clicky switch — stiff spring with a loud, firm click." },
  { name: "Gateron White", manufacturer: "Gateron", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 55, peak_decibels: 61, responsiveness_rating: 4, actuation_force: 35, description: "Light-spring clicky — fast actuation with a bright, airy click." },
  { name: "Gateron Silent Red", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 40, peak_decibels: 46, responsiveness_rating: 3, actuation_force: 45, description: "Silenced Red with dampened up/down stroke — ideal for office builds." },
  { name: "Gateron Silent Yellow", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 42, peak_decibels: 48, responsiveness_rating: 3, actuation_force: 50, description: "Heavier silenced linear for typists who want quiet without mush." },
  { name: "Gateron Silent Brown", manufacturer: "Gateron", switch_type: "Tactile", pitch_profile: "Low-pitched", avg_decibels: 42, peak_decibels: 48, responsiveness_rating: 3, actuation_force: 45, description: "Silenced tactile — retains the Brown bump with damped sound." },
  { name: "Gateron Silent Black", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 43, peak_decibels: 49, responsiveness_rating: 3, actuation_force: 50, description: "Heavy silenced linear — quiet with a firm, deliberate feel." },
  { name: "Gateron Low Profile Red", manufacturer: "Gateron", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 44, peak_decibels: 50, responsiveness_rating: 5, actuation_force: 50, description: "Low-profile linear for slim keyboards — short travel, quick return." },

  // ── KAILH ──────────────────────────────────────────────────
  { name: "Kailh Red", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Neutral", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 4, actuation_force: 50, description: "Kailh's standard linear — slightly stiffer spring than Gateron Red." },
  { name: "Kailh Black", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 3, actuation_force: 60, description: "Heavy linear — firm and deliberate with a deep bottom-out." },
  { name: "Kailh Speed Silver", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 46, peak_decibels: 52, responsiveness_rating: 5, actuation_force: 50, description: "Speed linear with actuation 1.2mm from the top — built for gaming." },
  { name: "Kailh Pro Burgundy", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 50, description: "Pro-series linear with a leaf-spring reworked for smoother travel." },
  { name: "Kailh BOX Red", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 50, description: "BOX-housing linear — dust/water resistant with a resonant, marbly tone." },
  { name: "Kailh BOX Pink", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 50, description: "BOX linear with a slightly softer sound than BOX Red." },
  { name: "Kailh NovelKeys Cream", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 55, description: "NovelKeys collab BOX linear — creamy and deep, a thock favorite." },
  { name: "Kailh Speed Gold", manufacturer: "Kailh", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 50, description: "Speed linear variant with a bright, crisp bottom-out." },
  { name: "Kailh Brown", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 3, actuation_force: 50, description: "Kailh's tactile Brown — comparable to Cherry Brown with a touch more grit." },
  { name: "Kailh Purple", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 3, actuation_force: 60, description: "Heavy tactile with a pronounced bump — for typists who want feedback." },
  { name: "Kailh BOX Brown", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Marbly", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 3, actuation_force: 50, description: "BOX-housing tactile — sealed switch with a rounded bump." },
  { name: "Kailh BOX Orange", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Marbly", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 3, actuation_force: 55, description: "BOX tactile with a sharper bump than BOX Brown." },
  { name: "Kailh Speed Copper", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 50, description: "Speed tactile — early, sharp bump with fast actuation." },
  { name: "Kailh Pro Purple", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 50, description: "Pro-series tactile with a smooth, medium bump." },
  { name: "Kailh Heavy Tactile", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 2, actuation_force: 70, description: "Very heavy tactile for maximum feedback — a finger workout." },
  { name: "Kailh Polia", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "Premium tactile with a long, smooth bump and deep sound." },
  { name: "Kailh Sage", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 3, actuation_force: 60, description: "Sharp, snappy tactile with a crisp bottom-out." },
  { name: "Kailh NovelKeys Sherbet", manufacturer: "Kailh", switch_type: "Tactile", pitch_profile: "Marbly", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "NovelKeys collab BOX tactile — rounded bump with a marbly tone." },
  { name: "Kailh Blue", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 57, peak_decibels: 63, responsiveness_rating: 3, actuation_force: 50, description: "Kailh's click-jacket switch — slightly crisper than Cherry Blue." },
  { name: "Kailh BOX White", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 54, peak_decibels: 60, responsiveness_rating: 4, actuation_force: 50, description: "BOX click-bar switch — sealed, sharp click with a clean tone." },
  { name: "Kailh BOX Jade", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 55, peak_decibels: 61, responsiveness_rating: 4, actuation_force: 50, description: "BOX click-bar with a heavier spring and sharper click than BOX White." },
  { name: "Kailh BOX Navy", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 58, peak_decibels: 64, responsiveness_rating: 2, actuation_force: 60, description: "Heavy BOX click-bar — deep, loud click for heavy-handed typists." },
  { name: "Kailh Speed Bronze", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 54, peak_decibels: 60, responsiveness_rating: 4, actuation_force: 50, description: "Speed click-bar — early, sharp click built for fast gaming." },
  { name: "Kailh Bronze", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 56, peak_decibels: 62, responsiveness_rating: 3, actuation_force: 50, description: "Standard click-bar switch — crisper and cleaner than click-jacket." },
  { name: "Kailh Pro Light Green", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 55, peak_decibels: 61, responsiveness_rating: 4, actuation_force: 50, description: "Pro-series clicky — smooth travel with a bright, defined click." },
  { name: "Kailh BOX Heavy Jade", manufacturer: "Kailh", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 57, peak_decibels: 63, responsiveness_rating: 2, actuation_force: 60, description: "Extra-heavy BOX Jade — the stiffest click in the BOX lineup." },

  // ── ZEALPC ─────────────────────────────────────────────────
  { name: "Zealios V2 (62g)", manufacturer: "ZealPC", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 62, description: "Premium factory-lubed tactile with a large, smooth bump." },
  { name: "Zealios V2 (65g)", manufacturer: "ZealPC", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 65, description: "Mid-weight Zealios V2 — same smooth bump, slightly heavier spring." },
  { name: "Zealios V2 (67g)", manufacturer: "ZealPC", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 67, description: "The enthusiast-favorite Zealios weight — big bump, deep thock." },
  { name: "Tealios V2", manufacturer: "ZealPC", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 67, description: "Premium factory-lubed linear — buttery smooth with a creamy tone." },
  { name: "Zilents V2", manufacturer: "ZealPC", switch_type: "Tactile", pitch_profile: "Low-pitched", avg_decibels: 42, peak_decibels: 48, responsiveness_rating: 3, actuation_force: 62, description: "Silenced Zealios — retains the big bump while muting the sound." },
  { name: "Healios", manufacturer: "ZealPC", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 41, peak_decibels: 47, responsiveness_rating: 3, actuation_force: 67, description: "Silenced linear — the quietest ZealPC switch, smooth and whisper-soft." },
  { name: "Sakurios", manufacturer: "ZealPC", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 67, description: "Pink-housing Tealios variant with a slightly softer bottom-out." },
  { name: "Roselios", manufacturer: "ZealPC", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 67, description: "Rose-gold Tealios variant — same smooth linear with pink housing." },

  // ── DROP / JWK ─────────────────────────────────────────────
  { name: "Drop Holy Panda", manufacturer: "Drop", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 4, actuation_force: 55, description: "The legendary tactile — sharp, prominent bump with a deep thock." },
  { name: "Drop Holy Panda X", manufacturer: "Drop", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 4, actuation_force: 55, description: "Recolored Holy Panda — same bump, brighter and clackier sound." },
  { name: "Drop JWK Daring", manufacturer: "Drop", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "JWICK tactile with a medium bump and clean, neutral tone." },
  { name: "Drop Kiwis", manufacturer: "Drop", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "Smooth medium tactile with a rounded bump and deep sound." },
  { name: "Drop Mauve", manufacturer: "Drop", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 55, description: "JWK linear — smooth and creamy with a deep, muted bottom-out." },
  { name: "Drop MiTo Laser", manufacturer: "Drop", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 5, actuation_force: 55, description: "MiTo collab JWK linear — bright, crisp, and quick." },

  // ── DUROCK / JWK ───────────────────────────────────────────
  { name: "Durock T1", manufacturer: "Durock", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 67, description: "The budget Holy Panda alternative — big bump, deep thock, great value." },
  { name: "Durock Shrimp", manufacturer: "Durock", switch_type: "Tactile", pitch_profile: "Low-pitched", avg_decibels: 43, peak_decibels: 49, responsiveness_rating: 3, actuation_force: 45, description: "Silenced tactile — quiet with a noticeable but damped bump." },
  { name: "Durock Koala", manufacturer: "Durock", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "T1-style tactile with a snappier, clackier bottom-out." },
  { name: "Durock L7 Linear", manufacturer: "Durock", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 67, description: "Heavy linear — smooth and deep with a firm spring." },
  { name: "Durock Piano", manufacturer: "Durock", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 63.5, description: "UHMWPE-stem linear — glassy smooth with a resonant, marbly sound." },
  { name: "Durock Lupine", manufacturer: "Durock", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 5, actuation_force: 62, description: "POM-stem linear — smooth and bright with a crisp bottom-out." },
  { name: "Durock Silenced Linear", manufacturer: "Durock", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 41, peak_decibels: 47, responsiveness_rating: 3, actuation_force: 60, description: "Factory-silenced linear for quiet builds with minimal mush." },
  { name: "Durock POM Linear", manufacturer: "Durock", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 67.5, description: "POM-housing linear — ultra-smooth with a deep, creamy tone." },
  { name: "Durock Daybreak", manufacturer: "Durock", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 67, description: "Medium-bump tactile with a deep, rounded thock." },
  { name: "Durock Lotus", manufacturer: "Durock", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 62, description: "Light tactile with a gentle, smooth bump and neutral sound." },

  // ── TECSEE ─────────────────────────────────────────────────
  { name: "Tecsee Purple Panda", manufacturer: "Tecsee", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "Holy-Panda-style tactile with a smooth, prominent bump." },
  { name: "Tecsee Diamond", manufacturer: "Tecsee", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Sharp tactile with a crisp, clacky bottom-out." },
  { name: "Tecsee Ruby", manufacturer: "Tecsee", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 55, description: "POM-stem linear — glassy smooth with a bright, marbly sound." },
  { name: "Tecsee Sapphire", manufacturer: "Tecsee", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 55, description: "Factory-lubed linear with a deep, creamy tone." },
  { name: "Tecsee Carrot", manufacturer: "Tecsee", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "Long-pole tactile — snappy bump with a clacky return." },
  { name: "Tecsee Neapolitan", manufacturer: "Tecsee", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "Strawberry-milk tactile — smooth bump with a sweet, deep sound." },

  // ── C³ / BSUN ──────────────────────────────────────────────
  { name: "Bsun Pine", manufacturer: "Bsun", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Long-pole tactile — sharp bump with a deep, resonant thock." },
  { name: "Bsun Anubis", manufacturer: "Bsun", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 4, actuation_force: 55, description: "Heavy tactile with a clacky, aggressive bottom-out." },
  { name: "C³ Tangerine (V2)", manufacturer: "C³", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 62, description: "UHMWPE-housing linear — ultra-smooth with a glassy, marbly tone." },
  { name: "C³ Kiwi", manufacturer: "C³", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "T1-style tactile with a smooth, rounded bump and deep sound." },
  { name: "C³ Taro Ball", manufacturer: "C³", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Long-pole tactile — big bump with a resonant, thocky bottom-out." },
  { name: "C³ Equalz", manufacturer: "C³", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "Medium tactile with a clean, neutral bump and smooth travel." },

  // ── SP-STAR ────────────────────────────────────────────────
  { name: "SP-Star Purple", manufacturer: "SP-Star", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 67, description: "Heavy tactile with a smooth, prominent bump and deep thock." },
  { name: "SP-Star Orange", manufacturer: "SP-Star", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 67, description: "Factory-lubed linear — buttery smooth with a creamy, muted tone." },
  { name: "SP-Star Lime", manufacturer: "SP-Star", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 67, description: "Sharp tactile with a bright, clacky bottom-out." },
  { name: "SP-Star Sakura Pink", manufacturer: "SP-Star", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 67, description: "Light linear with a glassy, marbly sound and smooth travel." },

  // ── OUTEMU ─────────────────────────────────────────────────
  { name: "Outemu Red", manufacturer: "Outemu", switch_type: "Linear", pitch_profile: "Neutral", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 3, actuation_force: 45, description: "Budget linear — slightly scratchy but unbeatable value." },
  { name: "Outemu Brown", manufacturer: "Outemu", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 3, actuation_force: 45, description: "Budget tactile — subtle bump, great for entry-level builds." },
  { name: "Outemu Blue", manufacturer: "Outemu", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 56, peak_decibels: 62, responsiveness_rating: 3, actuation_force: 50, description: "Budget clicky — loud and bright at a fraction of the cost." },
  { name: "Outemu Black", manufacturer: "Outemu", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 3, actuation_force: 60, description: "Budget heavy linear for firm, deliberate typing." },
  { name: "Outemu Lime", manufacturer: "Outemu", switch_type: "Clicky", pitch_profile: "High-pitched", avg_decibels: 54, peak_decibels: 60, responsiveness_rating: 4, actuation_force: 45, description: "Click-bar switch — cleaner click than click-jacket Outemu Blue." },
  { name: "Outemu Peach", manufacturer: "Outemu", switch_type: "Linear", pitch_profile: "Low-pitched", avg_decibels: 43, peak_decibels: 49, responsiveness_rating: 3, actuation_force: 40, description: "Light silenced linear — quiet and soft for office builds." },

  // ── AKKO ──────────────────────────────────────────────────
  { name: "Akko CS Silver", manufacturer: "Akko", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 46, peak_decibels: 52, responsiveness_rating: 5, actuation_force: 43, description: "Speed linear with a short actuation and bright, clacky tone." },
  { name: "Akko CS Jelly Pink", manufacturer: "Akko", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 45, description: "Jelly-housing linear — deep, thocky, and smooth for the price." },
  { name: "Akko CS Lavender Purple", manufacturer: "Akko", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 45, description: "Medium tactile with a smooth bump and deep, rounded sound." },
  { name: "Akko CS Matcha Green", manufacturer: "Akko", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 45, description: "Tactile with a pronounced bump and a deep, matcha-smooth feel." },
  { name: "Akko CS Banana Split", manufacturer: "Akko", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 45, description: "Budget tactile with a rounded bump — a great value Holy Panda feel." },
  { name: "Akko CS Cream Yellow", manufacturer: "Akko", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 4, actuation_force: 50, description: "Creamy linear with a deep, muted bottom-out and smooth travel." },
  { name: "Akko CS Safari", manufacturer: "Akko", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 45, description: "Medium tactile with a clean, neutral bump." },
  { name: "Akko CS Ocean Blue", manufacturer: "Akko", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 45, description: "Sharp tactile with a bright, clacky bottom-out." },

  // ── GLORIOUS ───────────────────────────────────────────────
  { name: "Glorious Lynx", manufacturer: "Glorious", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 55, description: "Factory-lubed linear — smooth and creamy with a deep tone." },
  { name: "Glorious Panda", manufacturer: "Glorious", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Holy-Panda-style tactile with a sharp, prominent bump." },
  { name: "Glorious Maple", manufacturer: "Glorious", switch_type: "Tactile", pitch_profile: "Neutral", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "Medium tactile with a smooth bump and neutral sound." },

  // ── WUQUE STUDIO (WS) ──────────────────────────────────────
  { name: "WS Morandi", manufacturer: "Wuque Studio", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "Long-pole tactile with a smooth, rounded bump and deep thock." },
  { name: "WS Heavy Tactile", manufacturer: "Wuque Studio", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 53, peak_decibels: 59, responsiveness_rating: 3, actuation_force: 60, description: "Heavy tactile — strong, deliberate bump for maximum feedback." },
  { name: "WS Autumn Forest", manufacturer: "Wuque Studio", switch_type: "Tactile", pitch_profile: "Clacky", avg_decibels: 52, peak_decibels: 58, responsiveness_rating: 4, actuation_force: 55, description: "Sharp tactile with a crisp, clacky bottom-out." },
  { name: "WS Yellow", manufacturer: "Wuque Studio", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 50, description: "Factory-lubed linear — creamy and deep with a smooth travel." },
  { name: "WS Moyun Black", manufacturer: "Wuque Studio", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 3, actuation_force: 50, description: "Heavy linear with a deep, thocky bottom-out." },
  { name: "WS Red", manufacturer: "Wuque Studio", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 4, actuation_force: 45, description: "Light linear — smooth and deep, a great budget thock pick." },

  // ── HMX ───────────────────────────────────────────────────
  { name: "HMX Macchiato", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 50, description: "UHMWPE-stem linear — glassy smooth with a bright, marbly sound." },
  { name: "HMX Poro", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 50, description: "Smooth linear with a resonant, marbly tone and quick return." },
  { name: "HMX Cheese", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 5, actuation_force: 50, description: "POM-stem linear — bright and clacky with a crisp bottom-out." },
  { name: "HMX Hibiscus", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Creamy", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 45, description: "Light linear — creamy and smooth with a deep, muted tone." },
  { name: "HMX Sakura", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 47, peak_decibels: 53, responsiveness_rating: 5, actuation_force: 45, description: "Smooth linear with a glassy, marbly sound and light spring." },
  { name: "HMX Meteor", manufacturer: "HMX", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 5, actuation_force: 50, description: "Bright, clacky linear with a crisp and resonant bottom-out." },

  // ── EVERGLIDE ─────────────────────────────────────────────
  { name: "Everglide Aqua King", manufacturer: "Everglide", switch_type: "Linear", pitch_profile: "Marbly", avg_decibels: 48, peak_decibels: 54, responsiveness_rating: 5, actuation_force: 55, description: "UHMWPE linear — ultra-smooth with a glassy, water-like sound." },
  { name: "Everglide Bamboo", manufacturer: "Everglide", switch_type: "Linear", pitch_profile: "Thocky", avg_decibels: 49, peak_decibels: 55, responsiveness_rating: 4, actuation_force: 55, description: "Deep linear with a woody, thocky tone and smooth travel." },
  { name: "Everglide Sunset", manufacturer: "Everglide", switch_type: "Linear", pitch_profile: "Clacky", avg_decibels: 50, peak_decibels: 56, responsiveness_rating: 4, actuation_force: 55, description: "Bright linear with a crisp, clacky bottom-out." },
  { name: "Everglide Tourmaline", manufacturer: "Everglide", switch_type: "Tactile", pitch_profile: "Thocky", avg_decibels: 51, peak_decibels: 57, responsiveness_rating: 4, actuation_force: 55, description: "Smooth tactile with a rounded bump and deep, thocky sound." },
];

// Manufacturer list derived from the database, sorted by switch count desc.
export const MANUFACTURERS = SWITCH_DATABASE.reduce((acc, s) => {
  acc[s.manufacturer] = (acc[s.manufacturer] || 0) + 1;
  return acc;
}, {});